server:
  port: 8761

spring:
  application:
    name: ms-discover

eureka:
  instance:
    hostname: ms-discover
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://ms-discover:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO