server:
  port: 8084

spring:
  datasource:
    url: jdbc:mariadb://ms-enseignant-db:3306/db_enseignant?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: enseignant_user
    password: passer123
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 10
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

  application:
    name: ms-enseignant

eureka:
  instance:
    hostname: ms-enseignant 
    prefer-ip-address: false  
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://ms-discover:8761/eureka  
    fetch-registry: true
    register-with-eureka: true
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always



logging:
  level:
    root: INFO
    org.springframework.cloud: DEBUG
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG