server:
  port: 8088

spring:
  application:
    name: ms-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:

        # ===== USER =====
        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/service-user/**
          filters:
            - StripPrefix=1

        # ===== CLASSE =====
        - id: ms-classe
          uri: lb://ms-classe
          predicates:
            - Path=/ms-classe/**
          filters:
            - StripPrefix=1

        # ===== ETUDIANT =====
        - id: ms-etudiant
          uri: lb://ms-etudiant
          predicates:
            - Path=/ms-etudiant/**
          filters:
            - StripPrefix=1

        # ===== NOTE =====
        - id: ms-note
          uri: lb://ms-note
          predicates:
            - Path=/ms-note/**
          filters:
            - StripPrefix=1

        # ===== ENSEIGNANT =====
        - id: ms-enseignant
          uri: lb://ms-enseignant
          predicates:
            - Path=/ms-enseignant/**
          filters:
            - StripPrefix=1

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
