server:
  port: 8081

spring:
  application:
    name: service-user

  # AJOUT OBLIGATOIRE : Resource Server JWT (Keycloak)
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/gestion-etudiants


      
# AJOUT OPTIONNEL : seulement si service-user crée des users Keycloak via API
keycloak:
  server-url: http://keycloak:8080
  realm: gestion-etudiants
  admin-realm: master
  client-id: gestion-etudiants-backend
  client-secret: dIewxUIhq0fYP2HWgYZeUGryvyOiX5ue

eureka:
  instance:
    hostname: service-user 
    prefer-ip-address: false  
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://ms-discover:8761/eureka  
    fetch-registry: true
    register-with-eureka: true
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    config-url: /service-user/v3/api-docs/swagger-config
    url: /service-user/v3/api-docs
    oauth2-redirect-url: http://localhost:8088/service-user/swagger-ui/oauth2-redirect.html
  server-url: http://localhost:8088/service-user
  
logging:
  level:
    root: INFO
    org.springframework.cloud: DEBUG
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG