server:
  port: 8081

spring:
  datasource:
    url: jdbc:mariadb://service-user-db:3306/db_user?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: user
    password: passer123
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

  application:
    name: service-user

  # ✅ AJOUT OBLIGATOIRE : Resource Server JWT (Keycloak)
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8180/realms/gestion-etudiants

# ✅ AJOUT OPTIONNEL : seulement si service-user crée des users Keycloak via API
app:
  keycloak:
    server-url: http://keycloak:8180
    realm: gestion-etudiants
    admin-realm: master
    admin-username: admin
    admin-password: admin

eureka:
  instance:
    hostname: service-user  # IMPORTANT: nom du conteneur
    prefer-ip-address: false  # Désactivé pour Docker
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://ms-discover:8761/eureka  # CORRIGÉ: ms-discover au lieu de localhost
    fetch-registry: true
    register-with-eureka: true
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.springframework.cloud: DEBUG
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG
